import turtle
window = turtle.Screen ()
window.setup (600, 550)
print ("This program is drawing a castle" )
bgcolor =  input("Input a background color, preferably light blue (Do not use white, green or yellow): ") 
window.bgcolor(bgcolor)


t = turtle.Turtle()
tcastle = turtle.Turtle()
tcastle1 = turtle.Turtle()
tcastle2 = turtle.Turtle()
tsun = turtle.Turtle()
tgrass = turtle.Turtle()
tground = turtle.Turtle()
tcloud = turtle.Turtle()
turtle = turtle.Turtle()

tground.speed (100)
tcastle.speed (100)
tcastle1.speed (100)
tcastle2.speed (100)

#ground
tground.penup()
tground.setposition (-350,-180)
tground.pencolor ("#f4a460")
tground.pendown()
tground.fillcolor("#f4a460")
tground.begin_fill()

for i in range(2):
    tground.forward (700)
    tground.right (90)
    tground.forward (100)
    tground.right (90)
    
tground.end_fill()

turtle.pensize (3)
t.speed (100)
t.pensize (3)

#grass
tgrass.pensize(5)
tgrass.speed (100)
tgrass.penup()
tgrass.pencolor ("green")
tgrass.left (180)
tgrass.forward (230)
tgrass.penup ()
tgrass.setposition (350,-180)
tgrass.pendown()
tgrass.fillcolor ("green")
tgrass.begin_fill()

for i in range(2):
    tgrass.forward(700)
    tgrass.right (90)
    tgrass.forward (28)
    tgrass.right (90)

tgrass.end_fill()

#big castle tower
tcastle.penup ()
tcastle.setposition (47,-55)
tcastle.pensize (3)
tcastle.pencolor ("grey")

tcastle.fillcolor("white")
tcastle.begin_fill()
tcastle.pendown ()
tcastle.left (90)
tcastle.forward (70)
tcastle.left (90)
tcastle.forward (60)
tcastle.left (90)
tcastle.forward (70)
tcastle.left (90)
tcastle.forward (60)
tcastle.end_fill()

#short castle tower 
tcastle1.penup ()
tcastle1.setposition (-75,-50)
tcastle1.pensize (3)
tcastle1.begin_fill ()
tcastle1.right (90)
tcastle1.forward (70)
tcastle1.right (90)
tcastle1.forward (35)
tcastle1.right (180)

tcastle1.pendown ()
tcastle1.pencolor ("grey")
tcastle1.fillcolor ("white")
tcastle1.forward (35)
tcastle1.left (90)
tcastle1.forward (70)


tcastle1.left (90)
tcastle1.forward (35)
tcastle1.left(90)
tcastle1.forward (70)
tcastle1.left (90)
tcastle1.forward (35)
tcastle1.end_fill ()
tcastle1.penup ()
tcastle1.left (90)
tcastle1.forward (70)
tcastle1.right (90)

#short castle roof
tcastle1.pendown ()
tcastle1.fillcolor("grey")
tcastle1.begin_fill() 
tcastle1.forward (8)
tcastle1.left (135)
tcastle1.forward (35)
tcastle1.left (90)
tcastle1.forward (35)
tcastle1.left (135)
tcastle1.forward (50)
tcastle1.end_fill ()
tcastle1.hideturtle()

#short castle2 tower 
tcastle2.penup ()
tcastle2.setposition (150,-50)
tcastle2.pensize (3)
tcastle2.begin_fill ()
tcastle2.right (90)
tcastle2.forward (70)
tcastle2.right (90)
tcastle2.forward (35)
tcastle2.right (180)

tcastle2.pendown ()
tcastle2.pencolor ("grey")
tcastle2.fillcolor ("white")
tcastle2.forward (35)
tcastle2.left (90)
tcastle2.forward (70)


tcastle2.left (90)
tcastle2.forward (35)
tcastle2.left(90)
tcastle2.forward (70)
tcastle2.left (90)
tcastle2.forward (35)
tcastle2.end_fill ()
tcastle2.penup ()
tcastle2.left (90)
tcastle2.forward (70)
tcastle2.right (90)

#short castle2 roof
tcastle2.pendown ()
tcastle2.fillcolor("grey")
tcastle2.begin_fill() 
tcastle2.forward (8)
tcastle2.left (135)
tcastle2.forward (35)
tcastle2.left (90)
tcastle2.forward (35)
tcastle2.left (135)
tcastle2.forward (50)
tcastle2.end_fill ()
tcastle2.hideturtle()

#roof
tcastle.left (90)
tcastle.forward (70)
tcastle.right (90)
tcastle.forward (20)
tcastle.fillcolor("grey")
tcastle.begin_fill()
tcastle.left (135)
tcastle.forward (70)
tcastle.left (90)
tcastle.forward (70)
tcastle.left (135)
tcastle.forward (20)
tcastle.end_fill()

tcastle.forward (30)
tcastle.left (90)
tcastle.forward (80)
tcastle.left (44)

#set location
t.pencolor('grey')
t.penup ()
t.left (-90)
t.forward (180)
t.right (90)
t.forward (120)
t.right (90)

#castle 1 curve
t.pendown ()
t.fillcolor("grey")
t.begin_fill()
t.forward (50)
t.left (90)
t.forward (20)
t.right (90)
t.forward (30)
t.right (90)
t.forward (25)
t.right (90)
t.forward (20)
t.left (90)
t.forward(10)
t.left(90)
t.forward (20)
t.right (90)
t.forward(25)
t.right(90)
t.forward (20)
t.left (90)
t.forward(10)
t.left(90)
t.forward (20)
t.right (90)
t.forward(25)
t.right(90)
t.forward (30)
t.right (90)
t.forward (75)
t.left (90)
t.end_fill ()

#castle 1 square
t.fillcolor("white")
t.begin_fill()
t.forward (50)
t.left (90)
t.forward (75)
t.left (90)
t.forward (50)
t.end_fill ()

#castle 2 crown
t.pencolor ("grey")
t.fillcolor("grey")
t.begin_fill()
t.forward (70)
t.left (90)
t.forward (20)
t.right (90)
t.forward (30)
t.right (90)
t.forward (25)
t.right (90)
t.forward (20)
t.left (90)
t.forward(10)
t.left(90)
t.forward (20)
t.right (90)
t.forward(25)
t.right(90)
t.forward (20)
t.left (90)
t.forward(10)
t.left(90)
t.forward (20)
t.right (90)
t.forward(25)
t.right(90)
t.forward(20)
t.left(90)
t.forward (10)
t.left (90)
t.forward (20)
t.right (90)
t.forward(25)
t.right(90)
t.forward(20)
t.left(90)
t.forward (10)
t.left (90)
t.forward (20)
t.right (90)
t.forward(25)
t.right (90)
t.forward (30)
t.right (90)
t.forward (145)
t.left (90)
t.end_fill ()

#Castle 2 rectangle
t.pendown ()
t.fillcolor("white")
t.begin_fill()
t.forward (120)
t.left (90)
t.forward (130)
t.left (90)
t.forward (120)
t.left (180)
t.end_fill ()

#Castle 3 Crown
t.fillcolor("Grey")
t.begin_fill()
t.forward (40)
t.left (90)
t.forward (25)
t.right (90)
t.forward (20)
t.left (90)
t.forward(10)
t.left(90)
t.forward (20)
t.right (90)
t.forward (25)
t.right (90)
t.forward (20)
t.left (90)
t.forward(10)
t.left(90)
t.forward (20)
t.right (90)
t.forward(25)
t.right(90)
t.forward (30)
t.right (90)
t.forward (95)
t.end_fill ()

#castle 3 square
t.fillcolor("white")
t.begin_fill()
t.left (90)
t.forward (50)
t.left (90)
t.forward (75)
t.left (90)
t.forward (50)
t.end_fill ()

t.right (90)
t.pendown ()

#castle 3 square
t.penup()
t.right (90)
t.forward (50)
t.right (90)
t.forward (135)
t.left (180)
t.pendown ()

#Door
t.fillcolor("dark grey")
t.begin_fill()
t.forward (35)
t.left (90)
t.forward (50)
t.left(45)
t.forward (20)
t.left (45)
t.forward (25)
t.left (90)
t.forward (64)
t.left (90)
t.forward (40)
t.left (180)
t.forward (40)
t.end_fill ()

t.forward (3)
t.right (90)
t.forward (64)
t.right (180)
t.forward (64)
t.right (90) 

#door
t.fillcolor("dark grey")
t.begin_fill()
t.forward (40)
t.right (90)
t.forward (50)
t.right (45)
t.forward (20)
t.right (45)
t.forward (25)
t.end_fill ()

#window
t.penup ()
t.forward (40)
t.left (90)
t.forward (40)

box_size = 10

#window 1
t.pendown ()
t.fillcolor("grey")
t.begin_fill()
t.forward (box_size)
t.left (90)
t.forward (box_size)
t.left (90)
t.forward (box_size)
t.left (90)
t.forward (box_size)
t.end_fill()

t.penup ()
t.left(180)
t.forward (80)

#window 2
t.pendown ()
t.fillcolor("grey")
t.begin_fill()
t.forward (box_size)
t.right (90)
t.forward (box_size)
t.right (90)
t.forward (box_size)
t.right (90)
t.forward (box_size)
t.end_fill()
t.penup ()
t.hideturtle ()

turtle.pencolor('grey')
turtle.penup ()
turtle.forward (15)
turtle.right (90)
turtle.pendown ()

#window 3
turtle.pendown ()
turtle.fillcolor("grey")
turtle.begin_fill ()
turtle.forward (box_size)
turtle.left (90)
turtle.forward (box_size)
turtle.left (90)
turtle.forward (box_size)
turtle.left (90)
turtle.forward (box_size)
turtle.end_fill()
turtle.penup ()

turtle.setposition (-88,-65)

#window
turtle.pendown ()
turtle.fillcolor("grey")
turtle.begin_fill ()
turtle.forward (box_size)
turtle.left (90)
turtle.forward (box_size)
turtle.left (90)
turtle.forward (box_size)
turtle.left (90)
turtle.forward (box_size)
turtle.end_fill()
turtle.penup ()
turtle.setposition (138,-75)
#window
turtle.pendown ()
turtle.fillcolor("grey")
turtle.begin_fill ()
turtle.forward (box_size)
turtle.left (90)
turtle.forward (box_size)
turtle.left (90)
turtle.forward (box_size)
turtle.left (90)
turtle.forward (box_size)
turtle.end_fill()

turtle.hideturtle ()

#sun
tsun.pensize(5)
tsun.penup()
tsun.setposition (200,130)
tsun.pendown()
tsun.color("orange", "yellow")
tsun.begin_fill()
tsun.circle(50)
tsun.end_fill()
tsun.hideturtle ()

#cloud
tcloud.setheading(90)
tcloud.fillcolor("white")
tcloud.penup()
tcloud.goto(-250,220)
tcloud.pendown()
tcloud.begin_fill()

def cloud():
    tcloud.pensize(5)
    tcloud.speed (100)
    tcloud.color("white")
    tcloud.circle (20)
    for i in range (10):
        tcloud.circle(i)
        tcloud.circle(10)
        tcloud.right(36)
        tcloud.forward(10)
    tcloud.right (130)
    tcloud.forward (50)
    tcloud.circle (20)
    tcloud.end_fill()

cloud()

tcloud.setheading(90)
tcloud.fillcolor("white")
tcloud.penup()
tcloud.goto(-100,210)
tcloud.pendown()
tcloud.begin_fill()

cloud()

tcloud.setheading(90)
tcloud.fillcolor("white")
tcloud.penup()
tcloud.goto(50,250)
tcloud.pendown()
tcloud.begin_fill()

cloud()

window.exitonclick()

